name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          always-auth: true
          registry-url: https://registry.npmjs.org
          # scope: "@octocat" # 如果你有特定的 scope，也可以配置
      - run: npm ci
      - run: npm run build --if-present
      - name: Publish to npm
        run: |
          cd dist
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
